import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const SUPABASE_URL='https://iddzcbknnddkonrcwgpt.supabase.co';
const PUBLISHABLE_KEY='sb_publishable_qYWrm4tJE1n80lJx7PFoEw_WCkcV1ZL';
const db=createClient(SUPABASE_URL,PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const REVIEW_ENDPOINT=`${SUPABASE_URL}/functions/v1/salute-event-review`;
const $=id=>document.getElementById(id);
const loginView=$('loginView'),appView=$('appView'),authError=$('authError'),rows=$('responseRows'),status=$('statusMessage');
let events=[],responses=[],invites=[],currentFilter='all',selected=null;
const purchase={actively_looking:'Actively looking',beginning_to_explore:'Beginning to explore',within_one_year:'Within one year',not_at_this_time:'Not at this time'};
const consult={yes:'Yes',maybe:'Maybe',no:'No'};
const fmt=v=>v?new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(v)):'—';
const clean=v=>(v===null||v===undefined||v==='')?'—':String(v);
const escapeCsv=v=>'"'+clean(v).replaceAll('"','""')+'"';

$('loginForm').addEventListener('submit',async e=>{e.preventDefault();authError.textContent='';const button=e.submitter||e.currentTarget.querySelector('button[type="submit"]'),label=button.textContent;button.disabled=true;button.textContent='Signing in…';try{const {data,error}=await db.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error){authError.textContent='We could not sign you in. Check your email and password.';return}await initialize(data.session)}catch(_error){authError.textContent='The dashboard could not open. Please refresh and try again.'}finally{button.disabled=false;button.textContent=label}});
$('signOut').addEventListener('click',()=>db.auth.signOut());
$('eventSelect').addEventListener('change',loadDashboard);
$('search').addEventListener('input',render);
$('inviteSearch').addEventListener('input',renderInvites);
$('singleInviteForm').addEventListener('submit',addSingleInvite);
$('bulkInviteForm').addEventListener('submit',addBulkInvites);
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.filter;render()}));
$('exportCsv').addEventListener('click',exportCsv);
$('closeDetail').addEventListener('click',()=>$('detailDialog').close());
$('approveRequest').addEventListener('click',()=>review('approved'));
$('declineRequest').addEventListener('click',()=>review('declined'));

async function initialize(session){if(!session){loginView.hidden=false;appView.hidden=true;return}if(session.user.email?.toLowerCase()!=='hello@salute.community'){await db.auth.signOut();authError.textContent='This account does not have access to SALUTE Events.';return}const {data:staff}=await db.from('staff_members').select('role,active').eq('user_id',session.user.id).maybeSingle();if(!staff?.active){await db.auth.signOut();authError.textContent='This account does not have access to SALUTE Events.';return}loginView.hidden=true;appView.hidden=false;$('userEmail').textContent=session.user.email;const {data,error}=await db.from('salute_event_pages').select('*').order('starts_at',{ascending:false});if(error){status.textContent='Events could not be loaded.';return}events=data||[];$('eventSelect').replaceChildren(...events.map(e=>new Option(`${e.title} · ${e.status}`,e.id)));await loadDashboard()}
async function loadDashboard(){await Promise.all([loadResponses(),loadInvites()])}
async function loadResponses(){const eventId=$('eventSelect').value;if(!eventId)return;status.hidden=false;status.textContent='Loading responses…';responses=[];for(let from=0;;from+=500){const {data,error}=await db.from('salute_event_responses').select('*').eq('event_id',eventId).order('updated_at',{ascending:false}).range(from,from+499);if(error){status.textContent='Responses could not be loaded.';return}responses.push(...(data||[]));if(!data||data.length<500)break}render()}
async function loadInvites(){const eventId=$('eventSelect').value;if(!eventId)return;setInviteMessage('Loading invitation list…');const {data,error}=await db.from('salute_event_invitees').select('id,full_name,email,normalized_email,created_at').eq('event_id',eventId).eq('active',true).order('created_at',{ascending:false});if(error){setInviteMessage('The invitation list could not be loaded.',true);return}invites=data||[];setInviteMessage('');renderInvites()}
function visible(){const q=$('search').value.trim().toLowerCase();return responses.filter(r=>{const filter=currentFilter==='all'||r.response_type===currentFilter||(r.response_type==='interest'&&r.review_status===currentFilter);const hay=[r.full_name,r.email,r.company,r.job_title].join(' ').toLowerCase();return filter&&(!q||hay.includes(q))})}
function render(){const list=visible();status.hidden=responses.length>0;status.textContent=responses.length?'':'No responses have been received yet.';rows.replaceChildren(...list.map(row));renderStats()}
function renderStats(){const counts=[['Total',responses.length],['Attending',responses.filter(r=>r.response_type==='rsvp'&&r.rsvp_status==='accept').length],['Declined',responses.filter(r=>r.response_type==='rsvp'&&r.rsvp_status==='decline').length],['Interest',responses.filter(r=>r.response_type==='interest').length],['Awaiting review',responses.filter(r=>r.response_type==='interest'&&r.review_status==='pending').length]];$('stats').replaceChildren(...counts.map(([label,value])=>{const d=document.createElement('div');d.className='stat';const b=document.createElement('b');b.textContent=value;const s=document.createElement('span');s.textContent=label;d.append(b,s);return d}))}
function row(r){const tr=document.createElement('tr');const cells=[null,responseLabel(r),clean(r.company),purchase[r.purchase_intent]||clean(r.purchase_intent),consult[r.consultation_interest]||clean(r.consultation_interest),fmt(r.updated_at),null,null];cells.forEach((value,i)=>{const td=document.createElement('td');if(i===0){const strong=document.createElement('strong');strong.textContent=r.full_name;const small=document.createElement('small');small.textContent=r.email;td.append(strong,small)}else if(i===6){const badge=document.createElement('span');badge.className='badge '+(r.response_type==='interest'?r.review_status:'');badge.textContent=r.response_type==='interest'?r.review_status:'received';td.append(badge)}else if(i===7){const b=document.createElement('button');b.className='row-action';b.textContent='Review';b.addEventListener('click',()=>openDetail(r));td.append(b)}else td.textContent=value;tr.append(td)});return tr}
function responseLabel(r){if(r.response_type==='interest')return 'Interest request';return r.rsvp_status==='accept'?'RSVP · Accept':'RSVP · Decline'}
function openDetail(r){selected=r;$('detailName').textContent=r.full_name;$('reviewNote').value=r.review_note||'';const data=[['Email',r.email],['Title',r.job_title],['Company / organization',r.company],['Response',responseLabel(r)],['Looking to purchase art',purchase[r.purchase_intent]||r.purchase_intent],['Coffee chat with Sadaf',consult[r.consultation_interest]||r.consultation_interest],['Dietary restrictions',r.has_dietary_restrictions===true?'Yes':r.has_dietary_restrictions===false?'No':'—'],['Dietary details',r.dietary_details],['What they hope to discover or collect',r.interest_note],['Submitted',fmt(r.updated_at)],['Consent version',`${r.privacy_version} / ${r.terms_version} / ${r.media_release_version}`]];$('detailBody').replaceChildren(...data.map(([label,value])=>{const d=document.createElement('div');d.className='datum'+((label.includes('discover')||label.includes('Consent'))?' wide':'');const small=document.createElement('small');small.textContent=label;const span=document.createElement('span');span.textContent=clean(value);d.append(small,span);return d}));$('reviewArea').hidden=r.response_type!=='interest';$('approveRequest').textContent=r.review_status==='approved'?'Approved':'Approve request';$('declineRequest').textContent=r.review_status==='declined'?'Declined':'Decline request';$('detailDialog').showModal()}
async function review(next){if(!selected||selected.response_type!=='interest')return;const a=$('approveRequest'),d=$('declineRequest');a.disabled=d.disabled=true;const note=$('reviewNote').value.trim()||null;try{const{data:{session}}=await db.auth.getSession();if(!session)throw new Error('Please sign in again.');const response=await fetch(REVIEW_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${session.access_token}`},body:JSON.stringify({id:selected.id,status:next,note})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'The request could not be updated.');const data=result.response,i=responses.findIndex(r=>r.id===data.id);responses[i]=data;selected=data;$('detailDialog').close();render();await loadInvites()}catch(error){alert(error.message||'The request could not be updated. Please try again.')}finally{a.disabled=d.disabled=false}}
function exportCsv(){const list=visible(),headers=['Event','Name','Email','Title','Company','Response type','RSVP status','Purchase intent','Consultation interest','Dietary restrictions','Dietary details','Interest note','Review status','Review note','Submitted'];const event=events.find(e=>e.id===$('eventSelect').value);const lines=[headers.map(escapeCsv).join(',')];for(const r of list)lines.push([event?.title,r.full_name,r.email,r.job_title,r.company,r.response_type,r.rsvp_status,purchase[r.purchase_intent]||r.purchase_intent,consult[r.consultation_interest]||r.consultation_interest,r.has_dietary_restrictions,r.dietary_details,r.interest_note,r.review_status,r.review_note,r.updated_at].map(escapeCsv).join(','));const blob=new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`salute-${event?.slug||'event'}-responses.csv`;a.click();URL.revokeObjectURL(a.href)}

function setInviteMessage(message,isError=false){const el=$('inviteMessage');el.textContent=message;el.classList.toggle('error',isError)}
function normalizeEmail(value){return value.trim().toLowerCase()}
function validEmail(value){return /^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(value)}
async function addSingleInvite(e){e.preventDefault();const button=e.submitter,name=$('inviteName').value.trim(),email=normalizeEmail($('inviteEmail').value);if(!validEmail(email)){setInviteMessage('Enter a valid email address.',true);return}button.disabled=true;try{await saveInvites([{event_id:$('eventSelect').value,full_name:name||null,email,normalized_email:email,active:true,source:'admin'}]);e.currentTarget.reset();setInviteMessage(`${email} can now RSVP directly.`);await loadInvites()}catch(error){setInviteMessage(error.message||'The guest could not be added.',true)}finally{button.disabled=false}}
async function addBulkInvites(e){e.preventDefault();const button=e.submitter,raw=$('bulkInviteEmails').value,values=[...new Set(raw.split(/[\s,;]+/).map(normalizeEmail).filter(Boolean))],invalid=values.filter(v=>!validEmail(v));if(!values.length){setInviteMessage('Paste at least one email address.',true);return}if(invalid.length){setInviteMessage(`Check these email addresses: ${invalid.slice(0,3).join(', ')}${invalid.length>3?'…':''}`,true);return}button.disabled=true;try{await saveInvites(values.map(email=>({event_id:$('eventSelect').value,full_name:null,email,normalized_email:email,active:true,source:'admin_bulk'})));e.currentTarget.reset();setInviteMessage(`${values.length} ${values.length===1?'email was':'emails were'} added.`);await loadInvites()}catch(error){setInviteMessage(error.message||'The email list could not be added.',true)}finally{button.disabled=false}}
async function saveInvites(records){for(let i=0;i<records.length;i+=200){const {error}=await db.from('salute_event_invitees').upsert(records.slice(i,i+200),{onConflict:'event_id,normalized_email'});if(error)throw error}}
function renderInvites(){const q=$('inviteSearch').value.trim().toLowerCase(),list=invites.filter(i=>!q||[i.full_name,i.email].join(' ').toLowerCase().includes(q));$('inviteCount').textContent=`${invites.length} approved`;$('inviteRows').replaceChildren(...list.map(inviteRow));if(!list.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=3;td.className='empty-row';td.textContent=invites.length?'No invitation-list matches.':'No approved RSVP emails yet.';tr.append(td);$('inviteRows').append(tr)}}
function inviteRow(invite){const tr=document.createElement('tr'),guest=document.createElement('td'),date=document.createElement('td'),action=document.createElement('td'),strong=document.createElement('strong'),small=document.createElement('small'),button=document.createElement('button');strong.textContent=invite.full_name||invite.email;small.textContent=invite.full_name?invite.email:'Email only';guest.append(strong,small);date.textContent=fmt(invite.created_at);button.className='row-action danger-link';button.textContent='Remove';button.addEventListener('click',()=>removeInvite(invite,button));action.append(button);tr.append(guest,date,action);return tr}
async function removeInvite(invite,button){if(!confirm(`Remove ${invite.email} from the approved RSVP list?`))return;button.disabled=true;const {error}=await db.from('salute_event_invitees').update({active:false,updated_at:new Date().toISOString()}).eq('id',invite.id);if(error){setInviteMessage('The email could not be removed.',true);button.disabled=false;return}setInviteMessage(`${invite.email} was removed.`);await loadInvites()}

db.auth.onAuthStateChange((_event,session)=>setTimeout(()=>initialize(session),0));
const {data:{session}}=await db.auth.getSession();await initialize(session);
