import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const SUPABASE_URL='https://iddzcbknnddkonrcwgpt.supabase.co';
const PUBLISHABLE_KEY='sb_publishable_qYWrm4tJE1n80lJx7PFoEw_WCkcV1ZL';
const db=createClient(SUPABASE_URL,PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const REVIEW_ENDPOINT=`${SUPABASE_URL}/functions/v1/salute-event-review`;
const MANUAL_RSVP_ENDPOINT=`${SUPABASE_URL}/functions/v1/salute-event-manual-rsvp`;
const $=id=>document.getElementById(id);
const loginView=$('loginView'),appView=$('appView'),authError=$('authError'),rows=$('responseRows'),status=$('statusMessage');
let events=[],responses=[],invites=[],currentFilter='all',selected=null,responseLoadVersion=0,inviteLoadVersion=0;
const purchase={actively_looking:'Actively looking',beginning_to_explore:'Beginning to explore',within_one_year:'Within one year',not_at_this_time:'Not at this time'};
const consult={yes:'Yes',maybe:'Maybe',no:'No'};
const fmt=v=>v?new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(v)):'—';
const clean=v=>(v===null||v===undefined||v==='')?'—':String(v);
const escapeCsv=v=>'"'+clean(v).replaceAll('"','""')+'"';

$('loginForm').addEventListener('submit',async e=>{e.preventDefault();authError.textContent='';const button=e.submitter||e.currentTarget.querySelector('button[type="submit"]'),label=button.textContent;button.disabled=true;button.textContent='Signing in…';try{const {data,error}=await db.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error){authError.textContent='We could not sign you in. Check your email and password.';return}await initialize(data.session)}catch(_error){authError.textContent='The dashboard could not open. Please refresh and try again.'}finally{button.disabled=false;button.textContent=label}});
$('signOut').addEventListener('click',()=>db.auth.signOut());
$('eventSelect').addEventListener('change',loadDashboard);
$('search').addEventListener('input',render);
$('inviteSearch').addEventListener('input',renderInvites);
$('singleInviteForm').addEventListener('submit',addSingleInvite);
$('bulkInviteForm').addEventListener('submit',addBulkInvites);
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.filter;render()}));
$('exportCsv').addEventListener('click',exportCsv);
$('closeDetail').addEventListener('click',()=>$('detailDialog').close());
$('approveRequest').addEventListener('click',()=>review('approved'));
$('declineRequest').addEventListener('click',()=>review('declined'));
$('openManualRegistration').addEventListener('click',openManualRegistration);
$('closeManualRegistration').addEventListener('click',closeManualRegistration);
$('cancelManualRegistration').addEventListener('click',closeManualRegistration);
$('manualRegistrationForm').addEventListener('submit',saveManualRegistration);
$('manualRsvpStatus').addEventListener('change',updateManualDietary);
$('manualHasDietary').addEventListener('change',updateManualDietary);
$('resendManualConfirmation').addEventListener('click',resendManualConfirmation);

async function initialize(session){if(!session){loginView.hidden=false;appView.hidden=true;return}if(session.user.email?.toLowerCase()!=='hello@salute.community'){await db.auth.signOut();authError.textContent='This account does not have access to SALUTE Events.';return}const {data:staff}=await db.from('staff_members').select('role,active').eq('user_id',session.user.id).maybeSingle();if(!staff?.active){await db.auth.signOut();authError.textContent='This account does not have access to SALUTE Events.';return}loginView.hidden=true;appView.hidden=false;$('userEmail').textContent=session.user.email;const {data,error}=await db.from('salute_event_pages').select('*').order('starts_at',{ascending:false});if(error){status.textContent='Events could not be loaded.';return}events=data||[];$('eventSelect').replaceChildren(...events.map(e=>new Option(`${e.title} · ${e.status}`,e.id)));await loadDashboard()}
async function loadDashboard(){await Promise.all([loadResponses(),loadInvites()])}
async function loadResponses(){const eventId=$('eventSelect').value,version=++responseLoadVersion;if(!eventId)return;status.hidden=false;status.textContent='Loading responses…';const collected=[];for(let from=0;;from+=500){const {data,error}=await db.from('salute_event_responses').select('*').eq('event_id',eventId).order('updated_at',{ascending:false}).range(from,from+499);if(version!==responseLoadVersion)return;if(error){status.textContent='Responses could not be loaded.';return}collected.push(...(data||[]));if(!data||data.length<500)break}if(version!==responseLoadVersion)return;responses=collected;render()}
async function loadInvites(){const eventId=$('eventSelect').value,version=++inviteLoadVersion;if(!eventId)return;setInviteMessage('Loading invitation list…');const {data,error}=await db.from('salute_event_invitees').select('id,full_name,email,normalized_email,normalized_name,created_at').eq('event_id',eventId).eq('active',true).order('created_at',{ascending:false});if(version!==inviteLoadVersion)return;if(error){setInviteMessage('The invitation list could not be loaded.',true);return}invites=data||[];setInviteMessage('');renderInvites()}
function visible(){const q=$('search').value.trim().toLowerCase();return responses.filter(r=>{const confirmed=(r.response_type==='rsvp'&&r.rsvp_status==='accept')||(r.response_type==='interest'&&r.review_status==='approved');const filter=currentFilter==='all'||(currentFilter==='confirmed'&&confirmed)||r.response_type===currentFilter||(r.response_type==='interest'&&r.review_status===currentFilter);const hay=[r.full_name,r.email,r.company,r.job_title].join(' ').toLowerCase();return filter&&(!q||hay.includes(q))})}
function render(){const list=visible();status.hidden=responses.length>0;status.textContent=responses.length?'':'No responses have been received yet.';rows.replaceChildren(...list.map(row));renderStats()}
function renderStats(){const counts=[['Total',responses.length],['Confirmed',responses.filter(r=>(r.response_type==='rsvp'&&r.rsvp_status==='accept')||(r.response_type==='interest'&&r.review_status==='approved')).length],['Declined',responses.filter(r=>r.response_type==='rsvp'&&r.rsvp_status==='decline').length],['Interest',responses.filter(r=>r.response_type==='interest').length],['Awaiting review',responses.filter(r=>r.response_type==='interest'&&r.review_status==='pending').length]];$('stats').replaceChildren(...counts.map(([label,value])=>{const d=document.createElement('div');d.className='stat';const b=document.createElement('b');b.textContent=value;const s=document.createElement('span');s.textContent=label;d.append(b,s);return d}))}
function row(r){const tr=document.createElement('tr');const cells=[null,responseLabel(r),clean(r.company),purchase[r.purchase_intent]||clean(r.purchase_intent),consult[r.consultation_interest]||clean(r.consultation_interest),fmt(r.updated_at),null,null];cells.forEach((value,i)=>{const td=document.createElement('td');if(i===0){const strong=document.createElement('strong');strong.textContent=r.full_name;const small=document.createElement('small');small.textContent=r.email;td.append(strong,small)}else if(i===6){const badge=document.createElement('span');badge.className='badge '+(r.response_type==='interest'?r.review_status:(r.registration_source==='admin'?'manual':''));badge.textContent=r.response_type==='interest'?r.review_status:(r.registration_source==='admin'?'manually registered':'received');td.append(badge)}else if(i===7){const b=document.createElement('button');b.className='row-action';b.textContent='Review';b.addEventListener('click',()=>openDetail(r));td.append(b)}else td.textContent=value;tr.append(td)});return tr}
function responseLabel(r){if(r.response_type==='interest')return r.review_status==='approved'?'Approved guest':'Interest request';const label=r.rsvp_status==='accept'?'RSVP · Accept':'RSVP · Decline';return r.registration_source==='admin'?`${label} · Manual`:label}
function openDetail(r){selected=r;$('detailName').textContent=r.full_name;$('reviewNote').value=r.review_note||'';const data=[['Email',r.email],['Title',r.job_title],['Company / organization',r.company],['Response',responseLabel(r)],['Looking to purchase art',purchase[r.purchase_intent]||r.purchase_intent],['Coffee chat with Sadaf',consult[r.consultation_interest]||r.consultation_interest],['Dietary restrictions',r.has_dietary_restrictions===true?'Yes':r.has_dietary_restrictions===false?'No':'—'],['Dietary details',r.dietary_details],['What they hope to discover or collect',r.interest_note],['Entry source',r.registration_source==='admin'?'Manually registered by SALUTE':'Submitted by guest'],['Confirmation email',r.confirmation_status==='trigger_accepted'?'Sent to email provider':r.confirmation_status==='trigger_failed'?'Could not be triggered':'Not requested'],['Submitted',fmt(r.updated_at)],['Guest consent',r.registration_source==='admin'?'Not collected through this admin entry':`${r.privacy_version} / ${r.terms_version} / ${r.media_release_version}`]];$('detailBody').replaceChildren(...data.map(([label,value])=>{const d=document.createElement('div');d.className='datum'+((label.includes('discover')||label.includes('Consent'))?' wide':'');const small=document.createElement('small');small.textContent=label;const span=document.createElement('span');span.textContent=clean(value);d.append(small,span);return d}));$('manualEmailArea').hidden=r.registration_source!=='admin';$('reviewArea').hidden=r.response_type!=='interest';$('approveRequest').textContent=r.review_status==='approved'?'Approved':'Approve request';$('declineRequest').textContent=r.review_status==='declined'?'Declined':'Decline request';$('detailDialog').showModal()}
async function review(next){if(!selected||selected.response_type!=='interest')return;const a=$('approveRequest'),d=$('declineRequest');a.disabled=d.disabled=true;const note=$('reviewNote').value.trim()||null;try{const{data:{session}}=await db.auth.getSession();if(!session)throw new Error('Please sign in again.');const response=await fetch(REVIEW_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${session.access_token}`},body:JSON.stringify({id:selected.id,status:next,note})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'The request could not be updated.');const data=result.response,i=responses.findIndex(r=>r.id===data.id);responses[i]=data;selected=data;$('detailDialog').close();render();await loadInvites()}catch(error){alert(error.message||'The request could not be updated. Please try again.')}finally{a.disabled=d.disabled=false}}
function openManualRegistration(){$('manualRegistrationForm').reset();$('manualRsvpStatus').value='accept';$('manualSendConfirmation').checked=true;$('manualMessage').textContent='';updateManualDietary();$('manualRegistrationDialog').showModal()}
function closeManualRegistration(){$('manualRegistrationDialog').close()}
async function resendManualConfirmation(){if(!selected||selected.registration_source!=='admin')return;const button=$('resendManualConfirmation'),label=button.textContent;button.disabled=true;button.textContent='Sending…';try{const{data:{session}}=await db.auth.getSession();if(!session)throw new Error('Please sign in again.');const response=await fetch(MANUAL_RSVP_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${session.access_token}`},body:JSON.stringify({mode:'resend_confirmation',response_id:selected.id})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'The confirmation email could not be triggered.');selected.confirmation_status='trigger_accepted';selected.confirmation_triggered_at=new Date().toISOString();const i=responses.findIndex(r=>r.id===selected.id);if(i>=0)responses[i]=selected;openDetail(selected);alert('The confirmation email was accepted by the email provider.')}catch(error){alert(error.message||'The confirmation email could not be triggered.')}finally{button.disabled=false;button.textContent=label}}
function updateManualDietary(){const attending=$('manualRsvpStatus').value==='accept',yes=$('manualHasDietary').value==='yes';$('manualDietaryQuestion').hidden=!attending;$('manualHasDietary').required=attending;if(!attending)$('manualHasDietary').value='';$('manualDietaryDetails').hidden=!(attending&&yes);$('manualDietaryText').required=attending&&yes;if(!(attending&&yes))$('manualDietaryText').value=''}
async function saveManualRegistration(e){e.preventDefault();const button=e.submitter,label=button.textContent,message=$('manualMessage');message.textContent='';message.classList.remove('error');button.disabled=true;button.textContent='Saving…';try{const{data:{session}}=await db.auth.getSession();if(!session)throw new Error('Please sign in again.');const attending=$('manualRsvpStatus').value==='accept',dietary=$('manualHasDietary').value;const payload={event_id:$('eventSelect').value,first_name:$('manualFirstName').value,last_name:$('manualLastName').value,email:$('manualEmail').value,job_title:$('manualTitle').value,company:$('manualCompany').value,rsvp_status:$('manualRsvpStatus').value,purchase_intent:$('manualPurchase').value,consultation_interest:$('manualConsult').value,has_dietary_restrictions:attending?dietary==='yes':null,dietary_details:attending&&dietary==='yes'?$('manualDietaryText').value:null,send_confirmation:$('manualSendConfirmation').checked};const response=await fetch(MANUAL_RSVP_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${session.access_token}`},body:JSON.stringify(payload)});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'The registration could not be saved.');await loadDashboard();$('manualRegistrationDialog').close();const emailNote=!payload.send_confirmation?'':result.response?.confirmation_status==='trigger_accepted'?' The confirmation email was accepted by the email provider.':' The registration was saved, but the confirmation email could not be triggered.';alert(`${payload.first_name.trim()} ${payload.last_name.trim()} was ${payload.rsvp_status==='accept'?'registered as attending':'recorded as unable to attend'}.${emailNote}`)}catch(error){message.textContent=error.message||'The registration could not be saved.';message.classList.add('error')}finally{button.disabled=false;button.textContent=label}}
function exportCsv(){const list=visible(),headers=['Event','Name','Email','Title','Company','Response type','RSVP status','Purchase intent','Consultation interest','Dietary restrictions','Dietary details','Interest note','Review status','Review note','Entry source','Confirmation status','Submitted'];const event=events.find(e=>e.id===$('eventSelect').value);const lines=[headers.map(escapeCsv).join(',')];for(const r of list)lines.push([event?.title,r.full_name,r.email,r.job_title,r.company,r.response_type,r.rsvp_status,purchase[r.purchase_intent]||r.purchase_intent,consult[r.consultation_interest]||r.consultation_interest,r.has_dietary_restrictions,r.dietary_details,r.interest_note,r.review_status,r.review_note,r.registration_source==='admin'?'Manually registered by SALUTE':'Submitted by guest',r.confirmation_status,r.updated_at].map(escapeCsv).join(','));const blob=new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`salute-${event?.slug||'event'}-responses.csv`;a.click();URL.revokeObjectURL(a.href)}

function setInviteMessage(message,isError=false){const el=$('inviteMessage');el.textContent=message;el.classList.toggle('error',isError)}
function normalizeEmail(value){return value.trim().toLowerCase()}
function normalizeName(value){return value.trim().replace(/\s+/g,' ').toLowerCase()}
function validEmail(value){if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(value)||value.includes('..'))return false;const[local,domain]=value.split('@');return!!local&&!!domain&&!local.startsWith('.')&&!local.endsWith('.')&&!domain.startsWith('.')&&!domain.endsWith('.')}
function inviteRecord(name,email,source){const fullName=name.trim().replace(/\s+/g,' '),normalizedEmail=normalizeEmail(email);return{event_id:$('eventSelect').value,full_name:fullName||null,normalized_name:fullName?normalizeName(fullName):null,email:normalizedEmail||null,normalized_email:normalizedEmail||null,active:true,source}}
async function addSingleInvite(e){e.preventDefault();const form=e.currentTarget,button=e.submitter,first=$('inviteFirstName').value.trim(),last=$('inviteLastName').value.trim(),email=normalizeEmail($('inviteEmail').value);if(email&&!validEmail(email)){setInviteMessage('Enter a valid email address.',true);return}if(!email&&(!first||!last)){setInviteMessage('Enter an email address or both first and last name.',true);return}button.disabled=true;try{await saveInvites([inviteRecord([first,last].filter(Boolean).join(' '),email,'admin')]);form.reset();await loadInvites();setInviteMessage(`${[first,last].filter(Boolean).join(' ')||email} can now RSVP directly.`)}catch(error){setInviteMessage(error.message||'The guest could not be added.',true)}finally{button.disabled=false}}
function parseBulkInvites(raw){const records=[];for(const original of raw.split(/\n+/)){const line=original.trim();if(!line)continue;if(validEmail(normalizeEmail(line))){records.push(inviteRecord('',line,'admin_bulk'));continue}const parts=line.split(/[,;]/).map(v=>v.trim()).filter(Boolean);if(parts.length>1&&parts.every(v=>validEmail(normalizeEmail(v)))){parts.forEach(v=>records.push(inviteRecord('',v,'admin_bulk')));continue}const possibleEmail=parts.length>1?normalizeEmail(parts.at(-1)):'';if(parts.length>1&&validEmail(possibleEmail)){const name=parts.slice(0,-1).join(' ').trim();records.push(inviteRecord(name,possibleEmail,'admin_bulk'));continue}const words=line.replace(/\s+/g,' ').split(' ');if(words.length>=2){records.push(inviteRecord(line,'','admin_bulk'));continue}throw new Error(`Check this guest entry: ${line}`)}const seen=new Set();return records.filter(r=>{const key=r.normalized_email?`e:${r.normalized_email}`:`n:${r.normalized_name}`;if(seen.has(key))return false;seen.add(key);return true})}
async function addBulkInvites(e){e.preventDefault();const form=e.currentTarget,button=e.submitter;let records;try{records=parseBulkInvites($('bulkInviteEmails').value)}catch(error){setInviteMessage(error.message,true);return}if(!records.length){setInviteMessage('Enter at least one guest.',true);return}button.disabled=true;try{await saveInvites(records);form.reset();await loadInvites();setInviteMessage(`${records.length} ${records.length===1?'guest was':'guests were'} added.`)}catch(error){setInviteMessage(error.message||'The guest list could not be added.',true)}finally{button.disabled=false}}
async function saveInvites(records){for(const record of records){if(record.normalized_email){if(record.normalized_name){const {data:nameOnly,error:findError}=await db.from('salute_event_invitees').select('id').eq('event_id',record.event_id).eq('normalized_name',record.normalized_name).is('normalized_email',null).limit(1).maybeSingle();if(findError)throw findError;if(nameOnly){const{error}=await db.from('salute_event_invitees').update(record).eq('id',nameOnly.id);if(error)throw error;continue}}const{error}=await db.from('salute_event_invitees').upsert(record,{onConflict:'event_id,normalized_email'});if(error)throw error;continue}const{data:existing,error:findError}=await db.from('salute_event_invitees').select('id').eq('event_id',record.event_id).eq('normalized_name',record.normalized_name).is('normalized_email',null).limit(1).maybeSingle();if(findError)throw findError;if(existing){const{error}=await db.from('salute_event_invitees').update(record).eq('id',existing.id);if(error)throw error}else{const{error}=await db.from('salute_event_invitees').insert(record);if(error)throw error}}}
function renderInvites(){const q=$('inviteSearch').value.trim().toLowerCase(),list=invites.filter(i=>!q||[i.full_name,i.email].join(' ').toLowerCase().includes(q));$('inviteCount').textContent=`${invites.length} approved`;$('inviteRows').replaceChildren(...list.map(inviteRow));if(!list.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=3;td.className='empty-row';td.textContent=invites.length?'No invitation-list matches.':'No approved RSVP emails yet.';tr.append(td);$('inviteRows').append(tr)}}
function inviteRow(invite){const tr=document.createElement('tr'),guest=document.createElement('td'),date=document.createElement('td'),action=document.createElement('td'),strong=document.createElement('strong'),small=document.createElement('small'),button=document.createElement('button');strong.textContent=invite.full_name||invite.email;small.textContent=invite.email||(invite.full_name?'Name-approved · Email will be linked at RSVP':'Email only');guest.append(strong,small);date.textContent=fmt(invite.created_at);button.className='row-action danger-link';button.textContent='Remove';button.addEventListener('click',()=>removeInvite(invite,button));action.append(button);tr.append(guest,date,action);return tr}
async function removeInvite(invite,button){const label=invite.full_name||invite.email;if(!confirm(`Remove ${label} from the approved RSVP list?`))return;button.disabled=true;const {error}=await db.from('salute_event_invitees').update({active:false,updated_at:new Date().toISOString()}).eq('id',invite.id);if(error){setInviteMessage('The email could not be removed.',true);button.disabled=false;return}setInviteMessage(`${label} was removed.`);await loadInvites()}

db.auth.onAuthStateChange((_event,session)=>setTimeout(()=>initialize(session),0));
const {data:{session}}=await db.auth.getSession();await initialize(session);
